---
title: "Hedging-hyperprior-text-output"
author: "Steve Simon"
date: "June 19, 2017"
output: html_document
---


```{r initial-steps}
source("prelims.R")
```

```{r calculate-exact-bb-results}
# posterior distribution with nice data: x=18, n=60
a0 <-  4
b0 <- 16
x  <- 18
n  <- 60
a1 <- a0 + x
b1 <- b0 + (n-x)
# posterior mean
a1/(a1+b1)
# posterior 95% credibility interval
qbeta(c(0.025, 0.975), a1, b1)

# posterior mean with x=54, n=60
x  <- 54
n  <- 60
a2 <- a0 + x
b2 <- b0 + (n-x)
# posterior mean
a2/(a2+b2)
# posterior 95% credibility interval
qbeta(c(0.025, 0.975), a2, b2)
```

```{r draw-table-bb-nice}
library("rjags")
dat.bb <- list(a=4, b=16, x=18, n=60)
mod.bb <- jags.model("jbb.txt", dat.bb, quiet=TRUE)
update(mod.bb, 1000)
out.bb <- coda.samples(mod.bb, "pi", 1000)
summary(out.bb)
```

```{r draw-table-bb-nasty}
dat.bb <- list(a=4, b=16, x=54, n=60)
mod.bb <- jags.model("jbb.txt", dat.bb, quiet=TRUE)
update(mod.bb, 1000)
out.bb <- coda.samples(mod.bb, "pi", 1000)
summary(out.bb)
```

```{r draw-table-hedge-nasty}
dat.hedge.nasty <- list(a=4, b=16, x=54, n=60)
mod.hedge.nasty <- jags.model("jhedge.txt", dat.hedge.nasty, quiet=TRUE)
update(mod.hedge.nasty, 1000)
out.hedge.nasty <- coda.samples(mod.hedge.nasty, c("pi", "tau", "post.n"), 1000)
summary(out.hedge.nasty)
```

```{r draw-table-hedge-nice}
dat.hedge.nice <- list(a=4, b=16, x=18, n=60)
mod.hedge.nice <- jags.model("jhedge.txt", dat.hedge.nice, quiet=TRUE)
update(mod.hedge.nice, 1000)
out.hedge.nice <- coda.samples(mod.hedge.nice, c("pi", "tau", "post.n"), 1000)
summary(out.hedge.nice)
```

```{r draw-table-hierarchy-nasty}
dat.hierarchy.nasty <- list(x0=3, n0=18, x=54, n=60)
mod.hierarchy.nasty <- jags.model("jhierarchy.txt", dat.hierarchy.nasty, quiet=TRUE)
update(mod.hierarchy.nasty, 1000)
out.hierarchy.nasty <- coda.samples(mod.hierarchy.nasty, c("pi", "pi0", "a0", "b0"), 100000)
summary(out.hierarchy.nasty)
```

```{r draw-table-hierarchy-nice}
dat.hierarchy.nice <- list(x0=3, n0=18, x=18, n=60)
mod.hierarchy.nice <- jags.model("jhierarchy.txt", dat.hierarchy.nice, quiet=TRUE)
update(mod.hierarchy.nice, 1000)
out.hierarchy.nice <- coda.samples(mod.hierarchy.nice, c("pi", "pi0", "a0", "b0"), 100000)
summary(out.hierarchy.nice)
```

```{r draw-table-hierarchy-matched}
dat.hierarchy.matched <- list(x0=3, n0=18, x=12, n=60)
mod.hierarchy.matched <- jags.model("jhierarchy.txt", dat.hierarchy.matched, quiet=TRUE)
update(mod.hierarchy.matched, 1000)
out.hierarchy.matched <- coda.samples(mod.hierarchy.matched, c("pi", "pi0", "a0", "b0", "nx"), 100000)
summary(out.hierarchy.matched)
```

```{r draw-table-hierarchy-prior}
dat.hierarchy.prior <- list(x0=10, n0=20, x=0, n=0)
mod.hierarchy.prior <- jags.model("jhierarchy.txt", dat.hierarchy.prior, quiet=TRUE)
update(mod.hierarchy.prior, 1000)
out.hierarchy.prior <- coda.samples(mod.hierarchy.prior, c("pi", "pi0", "a0", "b0"), 100000)
summary(out.hierarchy.prior)
```

```{r stan-hierarchical-nasty}
dat_stan <- list(
  J=2, y=c(4, 54), n=c(20, 60)
)
f <- "stan_hierarchy.stan"
fit_stan1 <- stan(file=f, data=dat_stan,
  control = list(adapt_delta = 0.99),                  
  iter= 10000, warmup=1000, chains = 4)
fit_stan1                                         %>%
  as.data.frame                                 -> sim_gp1
pairs(fit_stan1)
summary(fit_stan1)
```

```{r stan-hierarchical-nice}
dat_stan <- list(
  J=2, y=c(4, 18), n=c(20, 60)
)
f <- "stan_hierarchy.stan"
fit_stan2 <- stan(file=f, data=dat_stan,
  control = list(adapt_delta = 0.99),                  
  iter= 10000, warmup=1000, chains = 4)
fit_stan2                                         %>%
  as.data.frame                                 -> sim_gp2
summary(fit_stan2)
pairs(fit_stan2)
```

```{r stan-hierarchical-match}
dat_stan <- list(
  J=2, y=c(4, 12), n=c(20, 60)
)
f <- "stan_hierarchy.stan"
fit_stan3 <- stan(file=f, data=dat_stan,
  control = list(adapt_delta = 0.99),                  
  iter= 10000, warmup=1000, chains = 4)
fit_stan3                                         %>%
  as.data.frame                                 -> sim_gp3
summary(fit_stan3)
pairs(fit_stan3)
```

```{r max-hedge-trace, eval=FALSE}
xlist <- c(5:9, 10*(1:9), 100*(1:9), 1000*(1:9))
nreps <- 100
alist <- sample(xlist, nreps, replace=TRUE)
blist <- sample(xlist, nreps, replace=TRUE)
m <- rep(NA, nreps)
i <- 0
for (i in 1:nreps) {
  m[i] <- max(calc_hedge_trace(g=999, a=alist[i], b=blist[i])$mn, na.rm=TRUE)
}
cat("\n")
range(m, na.rm=TRUE)
1 / max(m, na.rm=TRUE)
```

```{r save-everything}
save.image(file="hedge-output.RData")
```